#!/bin/sh

export DATABASE_URL="postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}"

echo "Waiting for postgres..."

while ! pg_isready -d "$DATABASE_URL" > /dev/null 2> /dev/null; do
    isready=$(pg_isready -d "$DATABASE_URL");
    echo "$isready"
    sleep 1
done

echo "PostgreSQL started"

echo "Making migrations..."
python manage.py makemigrations

echo "Migrating..."
python manage.py migrate

echo "Running server..."
python manage.py runserver 0.0.0.0:8000