version: '3'

volumes:
  local_postgres_data: {}
  local_postgres_data_backups: {}

services:
  django:
    build:
      context: .
      dockerfile: ./deploy/django/Dockerfile
    image: isthecatin_django
    depends_on:
      - postgres
    volumes:
      - .:/app
    env_file:
      - ./deploy/.envs/.django
      - ./deploy/.envs/.postgres
    ports:
      - "8000:8000"
    command: /start

  postgres:
    build:
      context: .
      dockerfile: ./deploy/postgres/Dockerfile
    image: isthecatin_postgres
    volumes:
      - local_postgres_data:/var/lib/postgresql/data
      - local_postgres_data_backups:/backups
    env_file:
      - ./deploy/.envs/.postgres
