# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-07-20 14:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Casualty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('time_taken', models.DateTimeField()),
                ('creature_type', models.CharField(max_length=100)),
                ('creature_name', models.CharField(max_length=100)),
                ('doa', models.BooleanField()),
                ('known_deceased', models.BooleanField()),
                ('additional_image', models.URLField()),
                ('guilty_cat', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Highlight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('comment', models.CharField(max_length=255)),
            ],
        ),
    ]
