# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-07-20 14:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='highlight',
            name='url',
            field=models.URLField(max_length=500),
        ),
    ]
