# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-18 21:18
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catflapsite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='timetaken',
            field=models.DateTimeField(default=datetime.datetime(2017, 2, 18, 21, 18, 15, 705959)),
            preserve_default=False,
        ),
    ]
