# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-27 12:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catflapsite', '0002_image_timetaken'),
    ]

    operations = [
        migrations.CreateModel(
            name='Casualty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('time_taken', models.DateTimeField()),
                ('creature_type', models.TextField()),
                ('creature_name', models.TextField()),
                ('doa', models.BooleanField()),
                ('known_deceased', models.BooleanField()),
                ('additional_image', models.URLField()),
                ('guilty_cat', models.URLField()),
            ],
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
