# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-02 15:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catflapsite', '0003_auto_20170327_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casualty',
            name='creature_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='casualty',
            name='creature_type',
            field=models.CharField(max_length=100),
        ),
    ]
