# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-25 12:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catflapsite', '0004_auto_20170402_1623'),
    ]

    operations = [
        migrations.CreateModel(
            name='Highlight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('comment', models.CharField(max_length=255)),
            ],
        ),
    ]
